(()=>{const C=(name,short,sofascoreId,base,city,titles,GOL,DEF,MEI,ATA)=>({name,short,sofascoreId,base,city,titles,players:[...GOL.map(name=>({name,pos:"GOL",age:null})),...DEF.map(name=>({name,pos:"DEF",age:null})),...MEI.map(name=>({name,pos:"MEI",age:null})),...ATA.map(name=>({name,pos:"ATA",age:null}))]});window.RC_DATA={season:2026,updated:"2026-09-19",clubs:[
C("Flamengo","FLA",5981,82,"Rio de Janeiro",9,
["Agustín Rossi","Andrew","Dyogo Alves","Leonardo Nannetti"],
["Danilo","Alex Sandro","Léo Pereira","Léo Ortiz","Emerson Royal","Guillermo Varela","Ayrton Lucas","Vitão","João Victor","Daniel Sales","Johnny Goes","Daniel Thuram","Daniel Carvalho Marinho"],
["Giorgian de Arrascaeta","Lucas Paquetá","Jorginho","Samuel Lino","Gonzalo Plata","Nicolás de la Cruz","Jorge Carrascal","Luiz Araújo","Erick Pulgar","Saúl Ñíguez","Everton","Lorran","Evertton Araújo","Pablo Lúcio","Caio Joshua","Luiz Felipe","Caio Garcia","Douglas Costa Telles"],
["Pedro","Bruno Henrique","Joaquín Freitas","Anthony Valencia","João Camargo","Josmar"]),
C("Palmeiras","PAL",1963,81,"São Paulo",12,
["Carlos Miguel","Marcelo Lomba","Bruno Bertinato"],
["Gustavo Gómez","Agustín Giay","Joaquín Piquerez","Murilo","Bruno Fuchs","Alexander Barboza","Khellven","Jefté","Arthur Gabriel"],
["Jhon Arias","Andreas Pereira","Mauricio","Felipe Anderson","Emiliano Martínez","Marlon Freitas","Lucas Evangelista","Erick Belé","Luis Pacheco","Larson","Fabio So"],
["Vitor Roque","José Manuel López","Paulinho","Ramón Sosa","Heittor","Miguel Cinoncelli Bilong"]),
C("Athletico","CAP",1967,75,"Curitiba",1,
["Santos","Mycael","Matheus Soares"],
["Lucas Esquivel","Gilberto","Gilberto Junior","Arthur Dias","Léo","Juan Felipe Aguirre","Carlos Terán","Dantas","Gastón Benavídez","Leonardo Derik","Claudinho"],
["Luiz Gustavo","Juan Portilla","Bruno Zapelli","Steven Mendoza","João Cruz","Dudu","Kerwin Vargas","Jádson","Isaac","Felipinho","Chiqueti","Alejandro García"],
["Kevin Viveros","Leozinho","Jorge Rivaldo","Renan Viana","Renan Peixoto Nepomuceno","Daniel Troiano"]),
C("Bahia","BAH",1955,77,"Salvador",2,
["Ronaldo","Léo Vieira","Guido Herrera","Victor Nascimento","Victor"],
["Santiago Ramos Mingo","David Duarte","Kanu","Luiz Gustavo","Román Gómez","Marcos Victor","José Guilherme","Fredi Gomes","Marco Moreno"],
["Everton Ribeiro","Luciano Juba","Jean Lucas","Rodrigo Nestor","Cristian Olivera","Caio Alexandre","Ruan Pablo","Michel Araújo","Nicolás Acevedo","Erick","Mateo Sanabria","Vitinho","Lautaro López"],
["Erick Pulga","Alejo Véliz","Willian José","Dell","Everaldo","Ademir","Roger Gabriel"]),
C("Fluminense","FLU",1961,77,"Rio de Janeiro",4,
["Fábio","Marcelo Pitaluga","Vitor Eudes"],
["Thiago Silva","Guilherme Arana","Ignácio","Samuel Xavier","Renê","Juan Pablo Freytes","Guga","Julián Millán","Igor Rabello","Jemmes","Júlio Fidelis","Jhonny"],
["Yeferson Soteldo","Jefferson Savarino","Agustín Canobbio","Martinelli","Luciano Acosta","Kevin Serna","Ganso","Hércules","Alisson","Nonato","Otávio","David Terans","Yago","Ruan Sales"],
["Hulk","Germán Cano","John Kennedy","Rodrigo Castillo","Riquelme Felipe","Matheus Reis"]),
C("Cruzeiro","CRU",1954,78,"Belo Horizonte",4,
["Cássio","Otávio Costa","Léo Aragão"],
["Fabrício Bruno","Fagner","William Furtado","Lucas Villalba","Jonathan Jesus","João Marcelo","Gabriel Rojas","Kauã Moraes"],
["Gerson","Matheus Pereira","Wesley","Keny Arroyo","Gabriel Pec","Zé Lucas","Marquinhos","Lucas Romero","Matheus Henrique","Lucas Silva","Wanderson","João Costa","Felipe Morais","Fabrizio Peralta"],
["Kaio Jorge","Luis Sinisterra","Néiser Villarreal","Luciano Rodríguez","Bruno Rodrigues","Chico da Costa","Kaique Kenji"]),
C("Atlético-MG","CAM",1977,77,"Belo Horizonte",3,
["Everson","Gabriel Delfim","Robert Alves","Pedro Cobra Rodrigues"],
["Renan Lodi","Lyanco","Ruan","Natanael","Vitor Hugo","Léo Duarte","Vitão","Kauã Pascini","Pedro Tocantins","Pedro Henrique Lemos Barbosa"],
["Reinier","Fred","Gustavo Scarpa","Victor Hugo","Alan Franco","Kevin Castaño","Maycon","Ángelo Preciado","Bernard","Tomás Cuello","Alexsander","Tomás Pérez","Mamady Cissé","Igor Gomes","Patrick","Índio","Gutte"],
["Dudu","Alan Minda","Mateo Cassierra","Thiago Borbas","Cauã Campos Soares"]),
C("Coritiba","CFC",1982,72,"Curitiba",1,
["Pedro Morisco","Keiller","Pedro Rangel","Benassi"],
["João Pedro Chermont","Maicon","Felipe Jonatan","Jacy Maranhão","Tinga","Tiago Cóser","Bruno Melo","Rodrigo Moledo"],
["Josué","Breno Lopes","Lucas Ronier","Joaquín Lavega","Brian Ocampo","Thiago Santos","Sebastián Gómez","Richard","Gustavo","Vini Paulista","Vitor Gonçalves Tissi"],
["Rodrigo Rodrigues","Keno","Pedro Rocha","Renato Marques","Fabinho","Eberth Araujo Nogueira"]),
C("RB Bragantino","RBB",1999,74,"Bragança Paulista",0,
["Tiago Volpi","Cleiton","Gustavo Reis","Fabrício","Fernando Costa"],
["Vanderlan","Juninho Capixaba","Guzmán Rodríguez","José Andrés Hurtado","Gustavo Marques","Alix Vinicius","Agustin Sant Anna","Eduardo Santos","Ryan Augusto","Cauê Nascimento"],
["Rodriguinho","Fabinho","Lucas Barbosa","Henry Mosquera","Matheus Fernandes","Gabriel Girotto","Ignacio Laquintana","José Herrera","Ignacio Sosa","Bruno Praxedes","Eric Ramires","Gustavo Neves","Davi Gomes","Marcelinho Braz"],
["Wallace Yan","Isidro Pitta","Eduardo Sasha","Fernando","Vinicinho","Bruno Goncalves","Gabriel Novaes","Jhuan Nunes Coelho","Kawê"]),
C("Santos","SAN",1968,75,"Santos",8,
["Gabriel Brazão","João Paulo","Diogenes","Rodrigo Falcão"],
["Rodinei","Igor Vinícius","Lucas Veríssimo","Gonzalo Escobar","Luan Peres","Vinicius Rodrigues Lira","Alexis Duarte","João Paulo Ananias","João Alencar"],
["Everton","Miguelito","Arthur","Benjamín Rollheiser","Álvaro Barreal","Gabriel Menino","Gabriel Bontempo","Willian Arão","Thaciano","Gustavo Caballero","Lima","João Schmidt","Mateus Xavier","Christian Oliva","Gustavinho","Enzo Duscov Boer","Pepê Fermino","Samuel Mendes"],
["Neymar","Gabriel Barbosa","Rony","Moisés"]),
C("Botafogo","BOT",1958,76,"Rio de Janeiro",3,
["Cristhian Loor","Warleson","Gabriel Batista","Rhyan Carvalho","Cléber Lucas"],
["Alex Telles","Vitinho","Nahuel Ferraresi","Mateo Ponte","Marçal","Kaio Pantaleão","Arthur Chaves","Jhoan Hernandez","Gabriel Justino","Kadu Santos","Paulinho","Caio Roque","Ythallo","Lucas Monzón","Kauã Branco","Anthony","Kawan Thomaz","Gabriel Abdias","Herick"],
["Hakim Ziyech","Danilo Santos","Álvaro Montoro","Allan","Cristian Medina","Jordan Barrera","Edenilson","Lucas Villalba","Domingos Andrade","Wallace Davi","Huguinho","Kauan Toledo","Caio Valle","Bernardo Valim","Victor Hugo"],
["Arthur Cabral","Tiquinho Soares","Júnior Santos","Kadir Barría","Matheus Martins","Danilo Pereira","Lucas Emanuel","Arthur Izaque"]),
C("São Paulo","SAO",1981,76,"São Paulo",6,
["Rafael","Young","Carlos Coronel","Felipe Gabriel Preis","João Pedro"],
["Robert Arboleda","Wendell","Enzo Díaz","Rafael Tolói","Sabino","Iago Borduchi","Domingos Duarte","Lucas Ramon","Igor Felisberto","Matheus Belém","Aurélio Buta","Nicolas Bosshardt","Luis Osorio","Isac"],
["Ferreirinha","Damián Bobadilla","Artur","Marcos Antônio","Cauly","Pablo Maia","Luan Santos","Cédric Soares","Lucca","Danielzinho","Pedro Ferreira","Newton","Victor Sá","Tetê","Djhordney Ferreira"],
["Lucas Moura","Jonathan Calleri","Luciano","Ryan Francisco","André Silva","Gustavo Santana"]),
C("Vitória","VIT",1962,71,"Salvador",0,
["Lucas Arcanjo","Alexandre Fintelman","Yuri Sena"],
["Cacá","Ramon","Luan Cândido","Emanuel Brítez","Camutanga","Jamerson","Nathan Mendes","Fabiano Souza","Mateusinho","Zé Marcos","Edu","Riccieli"],
["Erick","Matheuzinho","Walace","Tomás Pochettino","Gabriel Baralhas","Emmanuel Martínez","Osvaldo","Dudu","Diego Tarzia","Zé Vitor","Caique Gonçalves","Anderson Pato","Filipe Machado","Rúben Ramos Ismael","Lucas Silva","José Breno","Cauan Farias","Hiago Santos"],
["Marinho","Renato Kayzer","Renê Sousa","Fabrício Santos","Alex Bruno"]),
C("Corinthians","COR",1957,76,"São Paulo",7,
["Hugo Souza","Felipe Longo","Kauê"],
["Matheuzinho","Matheus Bidu","Gustavo Henrique","Gabriel Paulista","André Ramalho","Fabrizio Angileri","João Pedro Tchoca","Hugo","Pedro Milans","Léo Mana","Renato Santos"],
["Rodrigo Garro","André Carrillo","Breno Bidon","Raniele","Kaio César","Allan","André Luiz","Zakaria Labyad","Matheus Pereira","Charles","Dieguinho","Alex Santana","Luiz Gustavo Bahia"],
["Memphis Depay","Yuri Alberto","Jesse Lingard","Pedro Raul","Gui Negão","Vitinho","Kayke Ferrari"]),
C("Mirassol","MIR",21982,73,"Mirassol",0,
["Walter","Alex Muralha","Thomazella","Georgemy"],
["Reinaldo","Victor Luis","Lucas Oliveira","Willian Machado","Igor Formiga","João Victor","Gabriel Knesowitsch","Daniel Borges","Elias","Wesley Santos"],
["Eduardo","Japa","Chico","Gustavo Silva","Denilson","Shaylon","Fernandinho","Neto Moura","José Aldo","Wallisson Luiz","Gustavo Cazonatti","Luiz Filipe"],
["André Luis","Negueba","Alesson","Bruno Santos","Carlos Eduardo","Zé Roberto","Edson Carioca"]),
C("Grêmio","GRE",5926,74,"Porto Alegre",2,
["Weverton","Gabriel Grando","Thiago Beltrame","Gabriel Menegon"],
["Marcos Rocha","Walter Kannemann","Marlon","Fabián Balbuena","Caio Paulista","Wagner Leonardo","Gustavo Martins","João Pedro","Luis Guedes","Pedro Gabriel","Wallace","Diego Caito"],
["Erick Noriega","Cristian Pavón","Mathias Villasanti","Filip Krovinović","Francis Amuzu","Tiaguinho","Juan Nardoni","Dodi","Danilo Barbosa","Riquelme Freitas","Roger"],
["Carlos Vinícius","Martin Braithwaite","Tetê","José Enamorado","Jovane Cabral","Matheus Nascimento"]),
C("Vasco","VAS",1974,73,"Rio de Janeiro",4,
["Léo Jardim","Daniel Fuzato","Pablo"],
["Paulo Henrique","Carlos Cuesta","Lucas Piton","Cuiabano","Robert Renan","Puma Rodríguez","Lucas Freitas","Alan Saldivia","Riquelme","Riquelme Avellar","Walace Falcão","Paulinho","Bruno André Azevedo Ribeiro"],
["Andrés Gómez","Marino Hinestroza","Nuno Moreira","Thiago Mendes","Cauan Barros","Tchê Tchê","Johan Rojas","Santiago Sosa","Jair","Guilherme Estrella","Mateus Carvalho","Lukas Zuccarello","Alan Lescano","Loide Augusto","Ramon Rique","João Vitor Silva","Euder"],
["Facundo Colidio","Brenner","Claudio Spinelli","Adson","Bruno Duarte","David","Andrey Fernandes"]),
C("Internacional","INT",1966,74,"Porto Alegre",3,
["Matheus Cunha","Sergio Rochet","Anthoni","Kauan","Diego Esser"],
["Félix Torres","Alexandro Bernabei","Guillermo Maripán","Gabriel Mercado","Bruno Gomes","Victor Gabriel","Matheus Bahia","Braian Aguirre","Jose Juninho"],
["Alan Patrick","Paulinho Paula","Thiago Maia","Vitinho","Niclas Eliasson","Bruno Henrique","Rodrigo Villagra","Calebe Gonçalves","Ronaldo","Yago Noal","Allex","Benjamin Arhin","Alisson Rodrigues de Melo","João Victor Alves de Morais Francisco","Gabriel Vinicius","Kempes"],
["Antonio Sanabria","Johan Carbonero","Kayky","Alerrandro","Raykkonen Pereira Soares","Fabricio"]),
C("Remo","REM",2012,69,"Belém",0,
["Ivan","Marcelo Rangel","Ygor Vinhas"],
["Zé Ivaldo","João Lucas","Marllon","Mayk","Matheus Alexandre","Duplexe Tchamba","Marcelinho","Léo","Matheus Felipe","Cristian Gonzalez","Marlon Lopes","Caio Pereira Magalhães","Edson Kauã"],
["Yago Pikachu","Antonio Galeano","Vitor Bueno","Patrick","Zé Welison","Jajá","Leonel Picco","Jáderson","Zé Ricardo","David Braga","Franco Catarozzi","Edson Fernando"],
["Alef Manga","Gabriel Taliari","Gabriel Poveda","Eduardo Melo","Tico"]),
C("Chapecoense","CHA",21845,69,"Chapecó",0,
["Anderson","Rafael Santos","Matheus","Gabriel Werner"],
["Bruno Tubarão","Bruno Pacheco","Rafael Thyere","Gustavo Talles","Fernando","Heitor","Eduardo Doma","João Paulo","Mancha","Victor Caetano","Kauan","Vinícius Eduardo de Almeida","Fernando Carlos da Silva Filho","Luciano"],
["Camilo","Dylan Borrero","Robert Santos","Yago Felipe","Ênio","Max","Kevin Ramírez","Rafael Carvalheira","Vinicius Balieiro","Miguel Carvalho","Rubens Tadeu","Bruno Matias","Everton","David Antunes","Juan Ferreira Leite","Rosivan"],
["Yannick Bolasie","Maurício Garcez","Giovanni Augusto","Marcinho","Neto Pessoa","Franco Rossi","Tulio Eduardo","Kassio"])
],titleRanking:[["Palmeiras",12],["Flamengo",9],["Santos",8],["Corinthians",7],["São Paulo",6],["Cruzeiro",4],["Vasco",4],["Fluminense",4],["Internacional",3],["Atlético-MG",3],["Botafogo",3],["Bahia",2],["Grêmio",2],["Athletico",1],["Coritiba",1],["Guarani",1],["Sport",1]].map(([club,titles])=>({club,titles})),sources:{competition:"CBF + Sofascore",squads:"Sofascore (elencos consultados em 19/09/2026)",ratings:"OVR RC e POT RC são índices próprios do jogo."}}})();